### ISSUE TITLE
Exposed ports don't show up in host (Docker for Mac)

### ISSUE THREAD

**Issue by RaeesBhatti** [vyshane/kid#12]
### Problem

I'm not really sure about how this is supposed to work (I'm new to Kubernetes). But I guess that my Kubernetes `Services` with type `LoadBalancers` should be accessible by their ports. And they are not. The pods are working fine though, with no errors.
Here is the example config:

```
apiVersion: v1
kind: Service
metadata:
  name: name-nginx
  labels:
    app: name
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8081
      protocol: TCP
      name: https
  selector:
    app: name
    tier: frontend
  type: LoadBalancer
```
### Environment

OS Version:

```
OS X El Capitan: 10.11.5 (15F34)
```

`docker --version`: (It's Docker for Mac)

```
Docker version 1.12.0-rc3, build 91e29e8, experimental
```
