### ISSUE TITLE
Can't save configmaps 

### ISSUE THREAD

**Issue by playerjamesbattleground** [vyshane/kid#3]
Hi Vyshane,

Kid is almost prefect to me until I run it on my Macbook:

I used a simple configmap, given /path/to/config/my-config.properties 

> kubectl create configmap my-config --from-file /path/to/config

then tried to mount it to a Deployment with Volumes and mountVolumes

```
spec:
  containers:
  - name: my-deployment
    image: my-images:1
    ports:
    - containerPort: 10080
      name: http
    volumeMounts:
    - mountPath: /optconfig
      name: config
    - mountPath: /opt/secret
      name: secret
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: my-config
    - name: secret
      secret:
        secretName: my-secret
```

So as a comparison, I also had a secret mounted, and turned out only the secret worked, that I can see files under the mounted path /opt/secret, however, the configmap mounted folder /opt/config is empty.

I've seen the same issue with kubernetes official one-node docker command on Mac, and desperately trying to find a solution, if you could please help ...

Thanks in advance

James
